services:
  lindesbs.climan.maintenance.command:
    class: lindesbs\climan\Command\CliManMaintenanceCommand
    tags: ['console.command']
  lindesbs.climan.localconfig.command:
    class: lindesbs\climan\Command\CliManLocalconfigCommand
    tags: ['console.command']
  lindesbs.climan.frontenduser.command:
    class: lindesbs\climan\Command\CliManFrontendUserCommand
    tags: ['console.command']
  lindesbs.climan.db.command:
    class: lindesbs\climan\Command\CliManDBCommand
    tags: ['console.command']
